### ISSUE TITLE
Build problem

### ISSUE THREAD

**Issue by buyukkardes** [dotnetcurry/azure-media-services-mvc#1]
Hi,

When I try to build, I have many errors at Visual Studio. Here are some samples. Do you have any idea about that?

Error   2   Unable to find version '4.1.4.12333' of package 'DotNetOpenAuth.AspNet'.    AzureMediaPortal
Error   5   Unable to find version '4.1.4.12333' of package 'DotNetOpenAuth.OAuth.Core'.    AzureMediaPortal
Error   9   Unable to find version '1.8.2' of package 'jQuery'. AzureMediaPortal
Error   12  Unable to find version '2.2.0' of package 'knockoutjs'. AzureMediaPortal
Error   19  Unable to find version '4.0.20710.0' of package 'Microsoft.AspNet.WebApi.Core'. AzureMediaPortal
Error   25  Unable to find version '2.0.30116.0' of package 'Microsoft.jQuery.Unobtrusive.Ajax'.    AzureMediaPortal
Error   32  The command ""D:\projects\azure_media\azure-media-services-mvc.nuget\NuGet.exe" install "D:\projects\azure_media\azure-media-services-mvc\AzureMediaPortal\packages.config" -source ""  -NonInteractive -RequireConsent -solutionDir "D:\projects\azure_media\azure-media-services-mvc\ " " exited with code 1.    AzureMediaPortal

Thanks

**Comment by devcurry** [comment]
Hi,
The project uses Nuget Package Package Restore to restore packages. Can you confirm your machine is connected to the Internet and can reach www.nuget.org?

If you can do both, then try these steps:
1. In Visual Studio 2012, Go to Tools->Library Package Manager->Package Manager Settings. This will open an options dialog.
2. There is a checkbox - 'Allow NuGet to download missing packages during build'. Check it, click OK and re-try the build. It may take a while the first time, but it will download all the dependencies and do the build for you.

Let us know if it works.

**Comment by buyukkardes** [comment]
Seems ok now. Thanks for your support.
